# Generated by Django 3.2.16 on 2023-01-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_table', '0004_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'date')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
